swagger: '2.0'
info:
  description: |
    This is the CrowdShelf API.
  version: 2.0.1
  title: CrowsShelf API
  contact:
    url: 'www.github.com/crowdshelf'
    name: 'http://www.github.crowdshelf.io'
host: crowdshelf.herokuapp.com
basePath: /api
schemes:
  - http
paths:
  /books:
    put:
      tags:
        - books
      summary: Add a new or a changed book to the database
      description: ''
      operationId: addBook
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Book object to be added or changed
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Book'
        '409':
          description: Conflict
        '422':
          description: Unprocessable entity
    get:
      tags:
        - books
      summary: Get all books
      description: ''
      operationId: getBooks
      produces:
        - application/json
      parameters:
        - in: query
          name: isbn
          description: Get all books with given ISBN
          required: false
          type: string
        - in: query
          name: owner
          description: Get all books that the given user owns
          required: false
          type: string
        - in: query
          name: rentedTo
          description: Get all books that the given user rents
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
  '/books/{bookId}':
    get:
      tags:
        - books
      summary: Get book by Id
      description: ''
      operationId: getBookById
      produces:
        - application/json
      parameters:
        - in: path
          name: bookId
          description: Book id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Book'
        '404':
          description: Not found
  '/books/{bookId}/renter':
    get:
      tags:
        - books
      summary: Get all the renters of a book
      description: ''
      operationId: getAllRenters
      produces:
        - application/json
      parameters:
        - in: path
          name: bookId
          description: Id of book
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '404':
          description: Book not found
  '/books/{bookId}/renter/{userId}':
    put:
      tags:
        - books
      summary: Add a renter to a book
      description: ''
      operationId: addRenter
      parameters:
        - in: path
          name: bookId
          description: Id of book to add renter to
          required: true
          type: string
        - in: path
          name: userId
          description: Id of user to be added as a renter
          required: true
          type: string
      responses:
        '200':
          description: OK
        '409':
          description: Conflict
        '422':
          description: '?? esso hva skjer her'
    delete:
      tags:
        - books
      summary: Remove a renter from a book
      description: ''
      operationId: removeRenter
      parameters:
        - in: path
          name: bookId
          description: Id of book to remove renter from
          required: true
          type: string
        - in: path
          name: userId
          description: Id of user to be removed as a renter
          required: true
          type: string
      responses:
        '200':
          description: OK
        '409':
          description: Not a renter kanskje?
        '422':
          description: '?? esso hva skjer her'
  /crowds:
    post:
      tags:
        - crowds
      summary: Create a new crowd
      description: ''
      operationId: createCrowd
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: crowd to be created
          required: true
          schema:
            $ref: '#/definitions/Crowd'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Crowd'
        '409':
          description: 'Conflict: Crowd name already in use'
        '422':
          description: 'Unprocessable entity: Something wrong with form data'
    get:
      tags:
        - crowds
      summary: Get all crowds
      description: ''
      operationId: getCrowds
      produces:
        - application/json
      parameters:
        - in: query
          name: member
          description: Get the crowds which the given user id is a member of
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Crowd'
        '404':
          description: No crowds
  '/crowds/{crowdId}':
    get:
      tags:
        - crowds
      summary: Get crowd by Id
      description: ''
      operationId: getCrowd
      produces:
        - application/json
      parameters:
        - in: path
          name: crowdId
          description: Id of crowd to get
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Crowd'
        '404':
          description: Not found
    delete:
      tags:
        - crowds
      summary: Delete crowd by Id
      description: ''
      operationId: deleteCrowd
      parameters:
        - in: path
          name: crowdId
          description: Id of the crowd to delete
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Crowd not found
        '550':
          description: Permission denied. You need to be owner.
  '/crowds/{crowdId}/members/{userId}':
    put:
      tags:
        - crowds
      summary: Add a member to a crowd
      description: ''
      operationId: addMember
      parameters:
        - in: path
          name: crowdId
          description: Id of crowd to add a member to
          required: true
          type: string
        - in: path
          name: userId
          description: Id of user to add as member
          required: true
          type: string
      responses:
        '200':
          description: OK
        '409':
          description: asdsda
    delete:
      tags:
        - crowds
      summary: Remove a member from a crowd
      description: ''
      operationId: removeMember
      parameters:
        - in: path
          name: crowdId
          description: Id of crowd to remove a member from
          required: true
          type: string
        - in: path
          name: userId
          description: Id of user to remove as member
          required: true
          type: string
      responses:
        '200':
          description: OK
        '409':
          description: dasdasdad
  /users:
    post:
      tags:
        - users
      summary: Create user
      description: ''
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object to create
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: OK
    get:
      tags:
        - users
      summary: Get users
      description: ''
      operationId: getAllUser
      produces:
        - application/json
      parameters:
        - in: query
          name: name
          description: Get users with the given name
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '400':
          description: No users
  '/users/{userId}':
    get:
      tags:
        - users
      summary: Get user with the given Id
      description: ''
      operationId: getUser
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: Id of user to get.
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '404':
          description: User not found
definitions:
  User:
    type: object
    properties:
      _rev:
        type: string
      _id:
        type: string
      username:
        type: string
      name:
        type: string
      email:
        type: string
  Book:
    type: object
    properties:
      _rev:
        type: string
      _id:
        type: string
      isbn:
        type: string
      owner:
        type: string
      rentedTo:
        type: string
        description: 'user _id'
  Crowd:
    type: object
    properties:
      _rev:
        type: string
      _id:
        type: string
      name:
        type: string
      owner:
        type: string
        description: 'user _id'
      members:
        type: array
        items:
          type: string
          description: 'user _id'
